<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MayaJaal.Api</RootNamespace>
    <AssemblyName>MayaJaal.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MayaJaal.Shared\MayaJaal.Shared.csproj" />
  </ItemGroup>
</Project>
